spring:
  application:
    name: wordcount
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/metro
    username: root
    password: root
server:
  port: 8080

logging:
  level:
    org.apache.beam.demos: debug
